[package]
name = "chop_contigs"
version = "0.1.0"
authors = ["Ben Woodcroft <donttrustben@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
seq_io = "*"
log = "0.4.*"
env_logger = "0.6.*"
